name: CD tutorial

on:
  push:
    branches: [dev]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JS
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          yarn

      - name: Build project
        run: |
          yarn build

  deploy:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          script: |
            cd /opt/green-renovation-development
            git pull
            yarn
            yarn build
